print('======== Exercício 15 (Aluguel de carro) ========')

qtd = int(input('Informe a quantidade de dias utilizados: '))
km = int(input('Informe a distância percorrida: '))

print('=================================================')
print('==================NOTA FISCAL====================')
print('=================================================')
print('Aluguel de Carro\nDias utilizados: {}'.format(qtd))
print('Quilômetros percorridos: {}km'.format(km))
print('Preço total dos dias: R$ {}'.format(qtd * 60))
print('Preço total dos KMs percorridos: R$ {}'.format(km * 0.15))
print('Preço total à pagar: R$ {}'.format((qtd * 60) + (km * 0.15)))
print('=================================================')
print('===============OUTRAS INFORMAÇÕES================')
print('=================================================')
print('Preço da diária: R$60.0')
print('Preço por quilômetro: R$ 0.15')
print('=================================================')
print('======================FIM========================')
print('=================================================')
